baseurl = "kelimuttu.github.io/kartiniteknologi"
theme = "hello-friend-ng"

DefaultContentLanguage = "id"
publishDir = "docs"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Podcast tentang perempuan Indonesia di bidang teknologi."
  keywords = "Podcast, teknologi, perempuan"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"

[languages]
  [languages.en]
    title = "Kartini Teknologi"
    homeSubtitle = "Kartini Teknologi is a podcast that features Indonesian women in tech. Listen:"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"
    languageName = "English"

    [languages.en.params.logo]
      logoText = "Kartini Teknologi"
      logoHomeLink = "/en/"
    # or
    #
      path = "/img/developer-border.svg"
      alt = "Logo Kartini Teknologi"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/episodes/index.xml"
        weight = 3

[languages.id]
    title = "Kartini Teknologi"
    homeSubtitle = "Kartini Teknologi adalah podcast yang menampilkan perempuan Indonesia di dunia teknologi. Putar:"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"
    languageName = "Bahasa Indonesia"

    [languages.id.params.logo]
      logoText = "Kartini Teknologi"
      logoHomeLink = "/"
    # or
    #
      path = "/img/developer-border.svg"
      alt = "Logo Kartini Teknologi"

	# You can create a language based menu
    [languages.id.menu]
      [[languages.id.menu.main]]
        identifier = "beranda"
        name = "Beranda"
        url = "/"
        weight = 1
      [[languages.id.menu.main]]
        identifier = "tentang"
        name = "Tentang"
        url = "/tentang"
        weight = 2
      [[languages.id.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/episodes/index.xml"
        weight = 3
